[package]
name = "fasta-util"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[dependencies]
clap = { version = "3", features = ["derive"]}
crossbeam = "0.8"
memmap2 = "0.5"

[dev-dependencies]
rand = "0.8"